modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "CC-BY-4.0"

[[mods]]
modId = "ftbqkeys"
version = "${version}"
displayName = "FTBQLocalizationKeys"
displayURL = "https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch"
authors = "TexTrue, LocalizedMC"
description = '''
FTBQLocalizationKeys
'''
logoFile = "icon.png"

[[dependencies.ftbqkeys]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "architectury"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"