modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "CC-BY-4.0"

[[mods]]
modId = "ftbqkeys"
version = "${version}"
displayName = "FTBQLocalizationKeys"
displayURL = "https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch"
credits = "BlackAuresArt"
authors = "TexTrue, LocalizedMC"
description = '''
FTBQLocalizationKeys
'''
logoFile = "icon"

[[dependencies.ftbqkeys]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "architectury"
mandatory = true
versionRange = "[3,4)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "kubejs"
mandatory = true
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbqkeys]]
modId = "ftbquests"
mandatory = true
ordering = "AFTER"
side = "BOTH"
